CREATE TABLE `PASSWORD_USER` (
	`ID` bigint AUTO_INCREMENT NOT NULL,
	`DELETED` boolean DEFAULT false,
	`DELETED_AT` timestamp,
	`CREATED_AT` timestamp DEFAULT (now()),
	`UPDATED_AT` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`SALT` varchar(300),
	`USER_ID` bigint NOT NULL,
	CONSTRAINT `PASSWORD_USER_ID` PRIMARY KEY(`ID`)
);
--> statement-breakpoint
ALTER TABLE `TERMS_JOB_USER` DROP FOREIGN KEY `TERMS_JOB_USER_USER_ID_USERS_ID_fk`;
--> statement-breakpoint
ALTER TABLE `PASSWORD_USER` ADD CONSTRAINT `PASSWORD_USER_USER_ID_USERS_ID_fk` FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`ID`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `USERS` DROP COLUMN `PASSOWRD`;